In [1]:
#import all the required libraries
import pandas as pd
import selenium
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(4)

#Opening the website 
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [3]:
#Scraping the rank by passing the xpath
rank = driver.find_elements_by_xpath('//td[@align="center"][1]')
Rank=[]
for i in rank:
    Rank.append(i.text)
#Scraping the rank by passing the xpath

name = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]/a')
# Making a list and storing all the scraped data into it
Name=[]
for i in name:
    if i.text is None :
        Name.append("-") 
    else:
        Name.append(i.text)
        
#Scraping the artist by passing the xpath    
upload = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
# Making a list and storing all the scraped data into it
Uploader=[]
for i in upload:
    if i.text is None :
        Uploader.append("-") 
    else:
        Uploader.append(i.text)
        
#Scraping the views by passing the xpath        
view=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
# Making a list and storing all the scraped data into it
Views=[]
for i in view:
    Views.append(i.text)
    
#Scraping the date by passing the xpath   
date=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
# Making a list and storing all the scraped data into it
Date=[]
for i in date:
    Date.append(i.text)

In [4]:
print(len(Rank),len(Date),len(Views),len(Uploader),len(Name))

49 49 49 49 38

In [7]:
Rank=Rank[:38]
Uploader=Uploader[:38]
Views=Views[:38]
Date=Date[:38]

In [8]:
print(len(Rank),len(Date),len(Views),len(Uploader),len(Name))

38 38 38 38 38

In [11]:
#Saving all the scraped data into a dataframe(Youtube)
Youtube=pd.DataFrame({})
Youtube['Rank']=Rank
Youtube['Name']=Name
Youtube['Artist']=Uploader
Youtube['Views']=Views
Youtube['Date']=Date

In [12]:
#Viewing the DataFrame
Youtube

,Rank,Name,Artist,Views,Date
0,1.,Baby Shark Dance,Pinkfong Kids' Songs & Stories,8.81,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.40,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,5.47,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.35,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.14,"April 6, 2015"
5,6.,Uptown Funk,Get Movies,4.44,"January 31, 2012"
6,7.,Gangnam Style,Mark Ronson,4.20,"November 19, 2014"
7,8.,Sugar,Cocomelon – Nursery Rhymes,4.16,"May 2, 2018"
8,9.,Sorry,Miroshka TV,4.16,"February 27, 2018"
9,10.,Dame Tu Cosita,Psy,4.09,"July 15, 2012"
10,11.,Roar,ChuChu TV,3.93,"March 6, 2014"
11,12.,Counting Stars,Maroon 5,3.49,"January 14, 2015"
12,13.,Thinking Out Loud,Justin Bieber,3.44,"October 22, 2015"
13,14.,Dark Horse,El Chombo,3.39,"April 5, 2018"
14,15.,Faded,Katy Perry,3.37,"September 5, 2013"
15,16.,Shake It Off,OneRepublic,3.32,"May 31, 2013"
16,17.,Lean On,Ed Sheeran,3.27,"October 7, 2014"
17,18.,Girls Like You,Katy Perry,3.09,"February 20, 2014"
18,19.,Bailando,Cocomelon – Nursery Rhymes,3.08,"May 24, 2018"
19,20.,Let Her Go,Alan Walker,3.08,"December 3, 2015"
20,21.,Mi Gente,Taylor Swift,3.07,"August 18, 2014"
21,22.,Perfect,Major Lazer,3.05,"March 22, 2015"
22,23.,Waka Waka (This Time for Africa),Maroon 5,3.05,"May 31, 2018"
23,24.,Hello,Enrique Iglesias,3.05,"April 11, 2014"
24,25.,Axel F,Passenger,3.01,"July 25, 2012"
25,26.,Pinkfong,J Balvin,2.93,"June 29, 2017"
26,27.,Luis Fonsi,Ed Sheeran,2.87,"November 9, 2017"
27,28.,Wiz Khalifa,Shakira,2.85,"June 4, 2010"
28,29.,Psy,Adele,2.85,"October 22, 2015"
29,30.,Justin Bieber,Crazy Frog,2.84,"June 16, 2009"
30,,Lady Gaga,"7,037,500,000","June 17, 2016","November 2, 2020"
31,[114],Judson Laipply,"2,993,700,000","January 12, 2017","August 4, 2017"
32,[28],RCA Records,"2,894,000,000","April 6, 2015","July 10, 2017"
33,[35],Judson Laipply,"803,700,000","July 15, 2012","November 24, 2012"
34,[115],Judson Laipply,"245,400,000","February 19, 2010","July 16, 2010"
35,93,Smosh,"178,400,000","November 24, 2009","April 14, 2010"
36,171,Nikesoccer,"128,900,000","May 22, 2007","October 25, 2009"
37,176,jawed,"118,900,000","April 6, 2006","May 2, 2009"

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [13]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(4)
# Opening the homepage of bcci website
driver.get("https://www.bcci.tv/")
# Clickking on drop down navigation bar On International
driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']").click()
# Selecting the Fixtures from International
driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a").click()

In [14]:
# Creating lists of each column
Match=[]
Place=[]
Series=[]
Time=[]
Date=[]
Month=[]

# Scraping the title by passing xpath
match=driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
# Appending all the match titles to the list (Match) using for loop
for i in match:
    Match.append(i.text)
# Scraping the place by passing xpath
place = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
# Appending all the places to the list (Place) using for loop
for i in place:
    Place.append(i.text)
# Scraping the Series by passing xpath
series=driver.find_elements_by_xpath("//div[@class='fixture__info u-skewed']/div[1]/span[1]")
# Appending all the Series to the list (Series) using for loop
for i in series:
    Series.append(i.text)
# Scraping the time by passing xpath
time=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[2]")
# Appending all the match timings to the list (Time) using for loop
for i in time:
    Time.append(i.text)
# Scraping the date by passing xpath
date=driver.find_elements_by_xpath("//div[@class='fixture__full-date']/span")
Date=[]
# Appending all the match dates to the list (Date) using for loop
for i in date:
    Date.append(i.text)
# Scraping the month by passing xpath
month=driver.find_elements_by_xpath("//div[@class='fixture__date-details']/span[1]")
# Appending all the months to the list (Month) using for loop
for i in month:
    Month.append(i.text)

In [15]:
# Saving all the scraped data into a dataframe named BCCI
BCCI=pd.DataFrame({})
BCCI['Match Title']=Match
BCCI['Series']=Series
BCCI['Place']=Place
BCCI['Date']=Date
BCCI['Month']=Month
BCCI['Time']=Time
# Viewing the Scraped data
BCCI

   Match Title Series                         Place Date      Month       Time
0        Final   TEST   The Ageas Bowl, Southampton   18       JUNE  15:00 IST
1      1st ODI    ODI  R Premadasa Stadium, Colombo   13       JULY  14:30 IST
2      2nd ODI    ODI  R Premadasa Stadium, Colombo   16       JULY  14:30 IST
3      3rd ODI    ODI  R Premadasa Stadium, Colombo   18       JULY  14:30 IST
4     1st T20I   T20I  R Premadasa Stadium, Colombo   21       JULY  19:00 IST
5     2nd T20I   T20I  R Premadasa Stadium, Colombo   23       JULY  19:00 IST
6     3rd T20I   T20I  R Premadasa Stadium, Colombo   25       JULY  19:00 IST
7     1st Test   TEST      Trent Bridge, Nottingham   04     AUGUST  15:30 IST
8     2nd Test   TEST                Lord's, London   12     AUGUST  15:30 IST
9     3rd Test   TEST             Headingley, Leeds   25     AUGUST  15:30 IST
10    4th Test   TEST              The Oval, London   02  SEPTEMBER  15:30 IST
11    5th Test   TEST      Old Trafford, Manchester   10  SEPTEMBER  15:30 IST

3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [18]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
# Opening the homepage of guru99 website
driver.get("https://www.guru99.com/")
# Clicking on Selenium 
driver.find_element_by_xpath('//ul[@class="menu"]/li[3]').click()

In [19]:
# Clicking on Selenium Exception Handling (Common Exceptions List)
driver.find_element_by_xpath('//*[@id="g-mainbar"]/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]').click()

In [20]:
#Scraping the names by passing xpath
name=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
#Scraping the description by passing xpath
desc=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
# Making list named "Name" and appending all the exception names into it
Name=[]
for i in name:
    Name.append(i.text)

# Making list named "Desc" and appending all the Description of all the exceptions into it
Desc=[]
for i in desc:
    Desc.append(i.text)

In [21]:
# Saving all the scraped data into a DataFrame named "Exceptions"
Exceptions=pd.DataFrame({})
Exceptions['Name']=Name
Exceptions['Description']=Desc
# Viewing the DataFrame(Exceptions)
Exceptions

,Name,Description
0,Exception name,Description
1,ElementNotVisibleException,This type of Selenium exception occurs when an...
2,ElementNotSelectableException,This Selenium exception occurs when an element...
3,NoSuchElementException,This Exception occurs if an element could not ...
4,NoSuchFrameException,This Exception occurs if the frame target to b...
5,NoAlertPresentException,This Exception occurs when you switch to no pr...
6,NoSuchWindowException,This Exception occurs if the window target to ...
7,StaleElementReferenceException,This Selenium exception occurs happens when th...
8,SessionNotFoundException,The WebDriver is acting after you quit the bro...
9,TimeoutException,Thrown when there is not enough time for a com...
10,WebDriverException,This Exception takes place when the WebDriver ...
11,ConnectionClosedException,This type of Exception takes place when there ...
12,ElementClickInterceptedException,The command may not be completed as the elemen...
13,ElementNotInteractableException,This Selenium exception is thrown when any ele...
14,ErrorInResponseException,This happens while interacting with the Firefo...
15,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
16,ImeActivationFailedException,This expectation will occur when IME engine ac...
17,ImeNotAvailableException,It takes place when IME support is unavailable.
18,InsecureCertificateException,Navigation made the user agent to hit a certif...
19,InvalidArgumentException,It occurs when an argument does not belong to ...
20,InvalidCookieDomainException,This happens when you try to add a cookie unde...
21,InvalidCoordinatesException,This type of Exception matches an interacting ...
22,InvalidElementStateExceptio,It occurs when command can't be finished when ...
23,InvalidSessionIdException,This Exception took place when the given sessi...
24,InvalidSwitchToTargetException,This occurs when the frame or window target to...
25,JavascriptException,This issue occurs while executing JavaScript g...
26,JsonException,It occurs when you afford to get the session w...
27,NoSuchAttributeException,This kind of Exception occurs when the attribu...
28,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
29,NoSuchContextException,ContextAware does mobile device testing.
30,NoSuchCookieException,This Exception occurs when no cookie matching ...
31,NotFoundException,This Exception is a subclass of WebDriverExcep...
32,RemoteDriverServerException,This Selenium exception is thrown when the ser...
33,ScreenshotException,It is not possible to capture a screen.
34,SessionNotCreatedException,It happens when a new session could not be suc...
35,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
36,UnexpectedTagNameException,Happens if a support class did not get a web e...
37,UnhandledAlertException,This expectation occurs when there is an alert...
38,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
39,UnknownMethodException,This Exception happens when the requested comm...
40,UnreachableBrowserException,This Exception occurs only when the browser is...
41,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [22]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
# Opening the homepage of website
driver.get("http://statisticstimes.com/")
# Clicking on Read more
driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[2]/p[2]/a").click()

In [25]:
# Clicking on Economy
driver.find_element_by_xpath("//div[@class='navbar']/div[2]/button").click()

In [27]:
#start and end for scraping SGDP
tr_start=0
tr_end=33

In [28]:
# Scraping the rank by passing xpath
rank = driver.find_elements_by_xpath('//td[@class="data1"]')
# Scraping the state by passing xpath
state=driver.find_elements_by_xpath('//td[@class="name"]')
# Scraping the GSDPs of year 18 & 19 by passing xpath
gsdp_1819=driver.find_elements_by_xpath('//tr[@role="row"]/td[4]')
# Scraping the GSDPs of year 19 &20 by passing xpath
gsdp_1920=driver.find_elements_by_xpath('//tr[@role="row"]/td[3]')
# Scraping the GDP of each state by passing xpath
gdp=driver.find_elements_by_xpath('//tr[@role="row"]/td[6]')
# Scraping the share of state by passing xpath
share=driver.find_elements_by_xpath('//tr[@role="row"]/td[5]')

# Making  a list named Rank and appending all the ranks in it
Rank=[]
for i in rank[tr_start:tr_end]:
    Rank.append(i.text)

state=driver.find_elements_by_xpath('//td[@class="name"]')
# Making  a list named State and appending all the states in it
State=[]
for i in state[tr_start:tr_end]:
    State.append(i.text)
# Making  a list named GSDP_1819 and appending all the GSDPs of year 18 & 19  in it
GSDP_1819=[]
for i in gsdp_1819[tr_start:tr_end]:
    GSDP_1819.append(i.text)
# Making  a list named GSDP_1920 and appending all the GSDPs of year 19 & 20  in it   
GSDP_1920=[]
for i in gsdp_1920[tr_start:tr_end]:
    GSDP_1920.append(i.text)
    
# Making  a list named Share and appending all the states shares in it
Share=[]
for i in share[tr_start:tr_end]:
    Share.append(i.text)
# Making  a list named GDP and appending all the states GDP in it    
GDP=[]
for i in gdp[tr_start:tr_end]:
    GDP.append(i.text)

In [29]:
#Checking for the length for each column
print(len(Rank),len(State),len(GSDP_1819),len(GSDP_1819),len(Share),len(GDP))

33 33 33 33 33 33

In [30]:
#Saving all the scraped data into a DataFrame
Stats=pd.DataFrame({})
Stats['Rank']=Rank
Stats['State']=State
Stats['GSDP_1819']=GSDP_1819
Stats['GSDP_1920']=GSDP_1920
Stats['Share']=Share
Stats['GDP($ billion)']=GDP
#Viewing the DataFrame
Stats

,Rank,State,GSDP_1819,GSDP_1920,Share,GDP($ billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [31]:
#Viewing the scraped data without index
print(Stats.to_string(index=False))

Rank                      State  GSDP_1819  GSDP_1920   Share GDP($ billion)
   1                Maharashtra  2,632,792          -  13.94%        399.921
   2                 Tamil Nadu  1,630,208  1,845,853   8.63%        247.629
   3              Uttar Pradesh  1,584,764  1,687,818   8.39%        240.726
   4                    Gujarat  1,502,899          -   7.96%        228.290
   5                  Karnataka  1,493,127  1,631,977   7.91%        226.806
   6                West Bengal  1,089,898  1,253,832   5.77%        165.556
   7                  Rajasthan    942,586  1,020,989   4.99%        143.179
   8             Andhra Pradesh    862,957    972,782   4.57%        131.083
   9                  Telangana    861,031    969,604   4.56%        130.791
  10             Madhya Pradesh    809,592    906,672   4.29%        122.977
  11                     Kerala    781,653          -   4.14%        118.733
  12                      Delhi    774,870    856,112   4.10%        117.703
  13                    Haryana    734,163    831,610   3.89%        111.519
  14                      Bihar    530,363    611,804   2.81%         80.562
  15                     Punjab    526,376    574,760   2.79%         79.957
  16                     Odisha    487,805    521,275   2.58%         74.098
  17                      Assam    315,881          -   1.67%         47.982
  18               Chhattisgarh    304,063    329,180   1.61%         46.187
  19                  Jharkhand    297,204    328,598   1.57%         45.145
  20                Uttarakhand    245,895          -   1.30%         37.351
  21            Jammu & Kashmir    155,956          -   0.83%         23.690
  22           Himachal Pradesh    153,845    165,472   0.81%         23.369
  23                        Goa     73,170     80,449   0.39%         11.115
  24                    Tripura     49,845     55,984   0.26%          7.571
  25                 Chandigarh     42,114          -   0.22%          6.397
  26                 Puducherry     34,433     38,253   0.18%          5.230
  27                  Meghalaya     33,481     36,572   0.18%          5.086
  28                     Sikkim     28,723     32,496   0.15%          4.363
  29                    Manipur     27,870     31,790   0.15%          4.233
  30                   Nagaland     27,283          -   0.14%          4.144
  31          Arunachal Pradesh     24,603          -   0.13%          3.737
  32                    Mizoram     22,287     26,503   0.12%          3.385
  33  Andaman & Nicobar Islands          -          -       -              -

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [33]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
#Opening the github website
driver.get("https://github.com/")

In [34]:
# Clicking on the Explore drop down options
explore = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore.click()

In [35]:
# Clicking on "Trending" option
trending=driver.find_element_by_xpath('//ul[@class="list-style-none mb-3"]/li')
trending.click()

In [36]:
# Clicking on "Trending" option through dropdown options of Explore button
driver.find_element_by_xpath('//div[@class="d-flex flex-wrap flex-items-center flex-justify-center flex-md-justify-start text-center text-md-left"]/a[3]').click()

In [37]:
# Scraping the titles of each repository
title = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

# Making list named "Title" and appending all the titles into it
Title=[]
for i in title:
    Title.append(i.text)

# Scraping the description of each repository
desc=driver.find_elements_by_xpath("//p[@class='col-9 color-text-secondary my-1 pr-4']")
# Making list named "Desc" and appending all the descriptions into it
Desc=[]
for i in desc:
    if i.text is None :
        Desc.append("-") 
    else:
        Desc.append(i.text)
# Scraping the contributors of each repository        
cont=driver.find_elements_by_xpath("//div[@class='f6 color-text-secondary mt-2']/a[2]")
# Making list named "Contributors" and appending all the contributors count into it
Contributors=[]
for i in cont:
    if i.text is None :
        Contributors.append("-") 
    else:
        Contributors.append(i.text)
# Scraping the programming languages of each repository        
lang = driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']")
# Making list named "Language" and appending all the languages into it
Language=[]    
for i in lang:
    if i.text is None :
        Language.append("-") 
    else:
        Language.append(i.text)

In [38]:
#Checking the length of each list
print(len(Title),len(Desc),len(Contributors),len(Language))

25 24 25 23

In [39]:
#Saving all the scraped data into a DataFrame(GitHub)
GitHub=pd.DataFrame({})
GitHub['Title']=Title[:23]
GitHub['Desc']=Desc[:23]
GitHub['Contributors Count']=Contributors[:23]
GitHub['Language']=Language[:23]
#Viewing the DataFrame
GitHub

,Title,Desc,Contributors Count,Language
0,programthink / zhao,【编程随想】整理的《太子党关系网络》，专门揭露赵国的权贵,"2,118",Python
1,AkashSingh3031 / The-Complete-FAANG-Preparation,This repository contains all the DSA (Data-Str...,334,Jupyter Notebook
2,CaffeineMC / sodium-fabric,A Fabric mod designed to improve frame rates a...,307,Java
3,n8n-io / n8n,Free and open fair-code licensed node based Wo...,"1,331",TypeScript
4,facebookresearch / AugLy,"A data augmentations library for audio, image,...",59,Python
5,vxunderground / MalwareSourceCode,Collection of malware source code for a variet...,572,Assembly
6,abuanwar072 / Flutter-Responsive-Admin-Panel-o...,Responsive Admin Panel or Dashboard using Flutter,539,Dart
7,EssayKillerBrain / EssayKiller_V2,基于开源GPT2.0的初代创作型人工智能 | 可扩展、可进化,499,Python
8,organicmaps / organicmaps,"🍃 Organic Maps is a better fork of MAPS.ME, an...",43,C++
9,rustdesk / rustdesk,Yet another remote desktop software,489,Rust
10,algorithm-visualizer / algorithm-visualizer,🎆Interactive Online Platform that Visualizes A...,"5,640",JavaScript
11,academic / awesome-datascience,📝 An awesome Data Science repository to learn ...,"4,536",Go
12,megaease / easegress,A Cloud Native traffic orchestration system,194,HTML
13,TheBobPony / getwindows11.tech,For the website,22,Python
14,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,"24,667",Python
15,kwai / DouZero,[ICML 2021] DouZero: Mastering DouDizhu with S...,62,Python
16,programthink / opensource,【编程随想】收藏的开源项目清单,"1,392",Batchfile
17,facebookresearch / xcit,Official code Cross-Covariance Image Transform...,10,JavaScript
18,githubdev03 / RDP,A utility-first CSS framework for rapid UI dev...,"2,337",Jupyter Notebook
19,tailwindlabs / tailwindcss,🐸💬 - a deep learning toolkit for Text-to-Speec...,"1,984",Go
20,coqui-ai / TTS,A platform for building proxies to bypass netw...,120,C
21,v2fly / v2ray-core,stb single-file public domain libraries for C/C++,"1,630",C++
22,nothings / stb,"cross-platform (Qt), open-source (GPLv3) video...","5,547",Dart

6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [52]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
#Opening the billboard website
driver.get("https://www.billboard.com/ ")

In [53]:
#Clicking on Charts
driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/header/div/ul/li[1]/a').click()

In [54]:
#Clicking on Hot 100
driver.find_element_by_xpath('//div[@class="charts-landing__info--view-chart-holder"]').click()

In [55]:
#Scraping the song name by passing xpath
song= driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')

#Making a list and storing all the scraped data into it
Song=[]
for i in song:
    if i.text is None :
        Song.append("-")
    else:
        Song.append(i.text)
        
#Scraping the artist name by passing xpath
artist=driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')

#Making a list and storing all the scraped data into it
Artist=[]
for i in artist:
    if i.text is None :
        Artist.append("-")
    else:
        Artist.append(i.text)
        
#Scraping the last week rank by passing xpath
last_week = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')

#Making a list and storing all the scraped data into it
Last_week=[]
for i in last_week:
    if i.text is None :
        Last_week.append("-")
    else:   
        Last_week.append(i.text)
        
#Scraping the peak rank by passing xpath
peak = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')

#Making a list and storing all the scraped data into it
Peak=[]
for i in peak:
    if i.text is None :
        Peak.append("-")
    else:
        Peak.append(i.text)
        
#Scraping the weeks on board by passing xpath
weeks_on_board = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
#Making a list and storing all the scraped data into it
Weeks_on_Board=[]
for i in weeks_on_board:
    if i.text is None :
        Weeks_on_Board.append("-")
    else:
        Weeks_on_Board.append(i.text)

In [56]:
#Checking the length of each list
print(len(Song),len(Artist),len(Last_week),len(Peak),len(Weeks_on_Board))

100 100 100 100 100

In [57]:
#Saving all the scraped data into a DataFrame(Billboard)
Billboard=pd.DataFrame({})
Billboard['Song name']=Song 
Billboard['Artist name']=Artist 
Billboard['Last week rank']=Last_week 
Billboard['Peak rank']=Peak
Billboard['Weeks on Board']=Weeks_on_Board
#Viewing the DataFrame
Billboard

,Song name,Artist name,Last week rank,Peak rank,Weeks on Board
0,Butter,BTS,1,1,3
1,Good 4 U,Olivia Rodrigo,2,1,4
2,Levitating,Dua Lipa Featuring DaBaby,3,2,36
3,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,6,1,12
4,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),4,1,14
5,Save Your Tears,The Weeknd & Ariana Grande,5,1,26
6,Kiss Me More,Doja Cat Featuring SZA,7,5,9
7,Astronaut In The Ocean,Masked Wolf,9,6,17
8,Deja Vu,Olivia Rodrigo,8,3,10
9,Yonaguni,Bad Bunny,-,10,1
10,Montero (Call Me By Your Name),Lil Nas X,10,1,11
11,Without You,The Kid LAROI,11,8,27
12,Forever After All,Luke Combs,15,2,33
13,Rapstar,Polo G,14,1,9
14,Blinding Lights,The Weeknd,17,1,79
15,Hats Off,"Lil Baby, Lil Durk & Travis Scott",-,16,1
16,Drivers License,Olivia Rodrigo,13,1,22
17,Beautiful Mistakes,Maroon 5 Featuring Megan Thee Stallion,18,18,14
18,Traitor,Olivia Rodrigo,12,9,3
19,Late At Night,Roddy Ricch,-,20,1
20,Voice Of The Heroes,Lil Baby & Lil Durk,81,21,2
21,Best Friend,Saweetie Featuring Doja Cat,22,14,22
22,Heartbreak Anniversary,Giveon,23,17,17
23,Heat Waves,Glass Animals,25,24,21
24,Calling My Phone,Lil Tjay Featuring 6LACK,21,3,17
25,Favorite Crime,Olivia Rodrigo,16,16,3
26,Lost Cause,Billie Eilish,-,27,1
27,Happier,Olivia Rodrigo,20,15,3
28,Up,Cardi B,24,1,18
29,Mood,24kGoldn Featuring iann dior,30,1,44
...,...,...,...,...,...
70,Snowflakes,Tom MacDonald,-,71,1
71,Single Saturday Night,Cole Swindell,70,70,6
72,That's Facts,Lil Baby & Lil Durk,-,73,1
73,Made For You,Jake Owen,57,32,16
74,Your Power,Billie Eilish,60,10,6
75,No More Parties,Coi Leray Featuring Lil Durk,59,26,18
76,We're Good,Dua Lipa,54,31,17
77,One Too Many,Keith Urban Duet With P!nk,71,62,26
78,Please,Lil Baby & Lil Durk,-,79,1
79,Up The Side,"Lil Baby, Lil Durk & Young Thug",-,80,1
80,Minimum Wage,Blake Shelton,69,69,5
81,Miss The Rage,Trippie Redd & Playboi Carti,58,11,5
82,Way Less Sad,AJR,77,77,7
83,Hope Ur OK,Olivia Rodrigo,52,29,3
84,Quicksand,Morray,73,65,18
85,Arcade,Duncan Laurence,85,78,9
86,Straightenin,Migos,78,38,4
87,Gang Gang,Polo G & Lil Wayne,61,33,3
88,Drinkin' Beer. Talkin' God. Amen.,Chase Rice Featuring Florida Georgia Line,75,75,2
89,Follow You,Imagine Dragons,86,68,10
90,Chasing After You,Ryan Hurd With Maren Morris,87,87,7
91,Tell Em,Cochise & $NOT,64,64,2
92,4 Da Gang,42 Dugg & Roddy Ricch,74,67,10
93,Tombstone,Rod Wave,79,11,12
94,What's Next,Drake,76,1,14
95,Things A Man Oughta Know,Lainey Wilson,93,93,4
96,Country Again,Thomas Rhett,89,73,6
97,Drunk (And I Don't Wanna Go Home),Elle King & Miranda Lambert,92,79,7
98,If You Want To,Lil Baby & Lil Durk,-,99,1
99,Seeing Green,"Nicki Minaj, Drake & Lil Wayne",67,12,4

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

In [80]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")
#Opening the naukri website
driver.get("https://www.naukri.com/")

In [81]:
#Clicking on Recruiters
driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/ul[1]/li[2]/a').click()

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [61]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")

#Clicking on books
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [65]:
# Scraping the book names
book=driver.find_elements_by_xpath('//tr[@class="odd"]/td[2]')

Book=[]
for i in book:
    if i.text is None :
        Book.append("-") 
    else:
        Book.append(i.text)
# Scraping the author names      
author=driver.find_elements_by_xpath('//tr[@class="odd"]/td[3]')

Author=[]
for i in author:
    if i.text is None :
        Author.append("-") 
    else:
        Author.append(i.text)
# Scraping the volumes        
volumes=driver.find_elements_by_xpath('//tr[@class="odd"]/td[4]')

Volumes=[]
for i in volumes:
    if i.text is None :
        Volumes.append("-") 
    else:
        Volumes.append(i.text)
 # Scraping the  publishers       
publisher=driver.find_elements_by_xpath('//tr[@class="odd"]/td[5]')

Publisher=[]
for i in publisher:
    if i.text is None :
        Publisher.append("-") 
    else:
        Publisher.append(i.text)
 # Scraping the genres       
genre=driver.find_elements_by_xpath('//tr[@class="odd"]/td[6]')

Genre=[]
for i in genre:
    if i.text is None :
        Genre.append("-") 
    else:
        Genre.append(i.text)

In [66]:
#Saving all the scraped data into a DataFrame
Novels=pd.DataFrame({})
Novels['Book Name']=Book
Novels['Author Name']=Author
Novels['Volumes sold']=Volumes
Novels['Publisher']=Publisher
Novels['Genre']=Genre 
#Viewing the DataFrame
Novels

,Book Name,Author Name,Volumes sold,Publisher,Genre
0,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
1,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
2,Harry Potter and the Goblet of Fire,"Rowling, J.K.","3,583,215",Bloomsbury,Children's Fiction
3,Harry Potter and the Prisoner of Azkaban,"Rowling, J.K.","3,377,906",Bloomsbury,Children's Fiction
4,Harry Potter and the Half-blood Prince:Childre...,"Rowling, J.K.","2,950,264",Bloomsbury,Children's Fiction
5,Twilight,"Meyer, Stephenie","2,315,405","Little, Brown Book",Young Adult Fiction
6,Fifty Shades Freed,"James, E. L.","2,193,928",Random House,Romance & Sagas
7,New Moon,"Meyer, Stephenie","2,152,737","Little, Brown Book",Young Adult Fiction
8,Eclipse,"Meyer, Stephenie","2,052,876","Little, Brown Book",Young Adult Fiction
9,"Curious Incident of the Dog in the Night-time,The","Haddon, Mark","1,979,552",Random House,General & Literary Fiction
10,"Short History of Nearly Everything,A","Bryson, Bill","1,852,919",Transworld,Popular Science
11,Breaking Dawn,"Meyer, Stephenie","1,787,118","Little, Brown Book",Young Adult Fiction
12,"Gruffalo,The","Donaldson, Julia","1,781,269",Pan Macmillan,Picture Books
13,"Kite Runner,The","Hosseini, Khaled","1,629,119",Bloomsbury,General & Literary Fiction
14,"Thousand Splendid Suns,A","Hosseini, Khaled","1,583,992",Bloomsbury,General & Literary Fiction
15,"Time Traveler's Wife,The","Niffenegger, Audrey","1,546,886",Random House,General & Literary Fiction
16,Bridget Jones's Diary:A Novel,"Fielding, Helen","1,508,205",Pan Macmillan,General & Literary Fiction
17,Captain Corelli's Mandolin,"Bernieres, Louis de","1,352,318",Random House,General & Literary Fiction
18,Life of Pi,"Martel, Yann","1,310,176",Canongate,General & Literary Fiction
19,"Child Called It,A","Pelzer, Dave","1,217,712",Orion,Autobiography: General
20,Angela's Ashes:A Memoir of a Childhood,"McCourt, Frank","1,204,058",HarperCollins,Autobiography: General
21,Northern Lights:His Dark Materials S.,"Pullman, Philip","1,181,503",Scholastic Ltd.,Young Adult Fiction
22,Harry Potter and the Half-blood Prince,"Rowling, J.K.","1,153,181",Bloomsbury,Science Fiction & Fantasy
23,Man and Boy,"Parsons, Tony","1,130,802",HarperCollins,General & Literary Fiction
24,"No.1 Ladies' Detective Agency,The:No.1 Ladies'...","McCall Smith, Alexander","1,115,549","Little, Brown Book","Crime, Thriller & Adventure"
25,"PS, I Love You","Ahern, Cecelia","1,107,379",HarperCollins,General & Literary Fiction
26,"Shadow of the Wind,The","Zafon, Carlos Ruiz","1,092,349",Orion,General & Literary Fiction
27,"Broker,The","Grisham, John","1,087,262",Random House,"Crime, Thriller & Adventure"
28,"Subtle Knife,The:His Dark Materials S.","Pullman, Philip","1,037,160",Scholastic Ltd.,Young Adult Fiction
29,Delia's How to Cook:(Bk.1),"Smith, Delia","1,015,956",Random House,Food & Drink: General
30,"Boy in the Striped Pyjamas,The","Boyne, John","1,004,414",Random House Childrens Books G,Young Adult Fiction
31,"Amber Spyglass,The:His Dark Materials S.","Pullman, Philip","1,002,314",Scholastic Ltd.,Young Adult Fiction
32,"Men are from Mars, Women are from Venus:A Prac...","Gray, John","992,846",HarperCollins,Popular Culture & Media: General Interest
33,"Short History of Tractors in Ukrainian,A","Lewycka, Marina","986,115",Penguin,General & Literary Fiction
34,"Lord of the Rings,The","Tolkien, J. R. R.","967,466",HarperCollins,Science Fiction & Fantasy
35,"Interpretation of Murder,The","Rubenfeld, Jed","962,515",Headline,"Crime, Thriller & Adventure"
36,"Alchemist,The:A Fable About Following Your Dream","Coelho, Paulo","956,114",HarperCollins,General & Literary Fiction
37,Notes from a Small Island,"Bryson, Bill","931,312",Transworld,Travel Writing
38,Bridget Jones: The Edge of Reason,"Fielding, Helen","924,695",Pan Macmillan,General & Literary Fiction
39,I Can Make You Thin,"McKenna, Paul","905,086",Transworld,Fitness & Diet
40,"Summons,The","Grisham, John","869,671",Random House,"Crime, Thriller & Adventure"
41,Nigella Express,"Lawson, Nigella","862,602",Random House,Food & Drink: General
42,"Memory Keeper's Daughter,The","Edwards, Kim","845,858",Penguin,General & Literary Fiction
43,About a Boy,"Hornby, Nick","828,215",Penguin,General & Literary Fiction
44,"God Delusion,The","Dawkins, Richard","816,907",Transworld,Popular Science
45,White Teeth,"Smith, Zadie","815,586",Penguin,General & Literary Fiction
46,"Book Thief,The","Zusak, Markus","809,641",Transworld,General & Literary Fiction
47,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
48,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
49,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [67]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")


# Opening the IMDB website
driver.get("https://www.imdb.com/list/ls095964455/")

In [68]:
# Scraping the title of the webseries
title=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
# Scraping the year span of the webseries
year=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
# Scraping the genre of the webseries
genre=driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[5]")
# Scraping the runtime of the webseries
runtime = driver.find_elements_by_xpath("//p[@class='text-muted text-small']/span[3]")
# Scraping the tratings of the webseries
ratings=driver.find_elements_by_xpath('//div[@class="ipl-rating-widget"]/div[1]')
# Scraping the votes of the webseries
votes=driver.find_elements_by_xpath('//div[@class="lister-item-content"]/p[4]/span[2]')

#Making a list and storing all the scraped titles into it
Title=[]
for i in title:
    if i.text is None :
        Title.append("-") 
    else:
        Title.append(i.text)
#Making a list and storing all the scraped years into it
Year=[]    
for i in year:
    if i.text is None :
        Year.append("-") 
    else:
        Year.append(i.text)
#Making a list and storing all the scraped genres into it        
Genre=[]
for i in genre:
    if i.text is None :
        Genre.append("-") 
    else:
        Genre.append(i.text)
#Making a list and storing all the scraped runtime into it        
Runtime=[]
for i in runtime:
    if i.text is None :
        Runtime.append("-") 
    else:
        Runtime.append(i.text)
#Making a list and storing all the scraped ratingss into it        
Ratings=[]
for i in ratings:
    if i.text is None :
        Ratings.append("-") 
    else:
        Ratings.append(i.text)
#Making a list and storing all the scraped votes into it        
Votes=[]
for i in votes:
    if i.text is None :
        Votes.append("-") 
    else:
        Votes.append(i.text)

In [69]:
#Saving all the scraped data into a DataFrame
Series=pd.DataFrame({})
Series['Title']=Title 
Series['Year span']=Year
Series['Genre']=Genre
Series['Run time']=Runtime
Series['Ratings']=Ratings
Series['Votes']=Votes
#Viewing the DataFrame
Series

,Title,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,825,442"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"865,452"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"875,270"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"262,969"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"224,366"
5,Orange Is the New Black,(2013–2019),"Comedy, Crime, Drama",59 min,8,"282,817"
6,Riverdale,(2017– ),"Crime, Drama, Mystery",45 min,6.8,"125,210"
7,Grey's Anatomy,(2005– ),"Drama, Romance",41 min,7.5,"261,685"
8,The Flash,(2014– ),"Action, Adventure, Drama",43 min,7.6,"314,818"
9,Arrow,(2012–2020),"Action, Adventure, Crime",42 min,7.5,"412,511"
10,Money Heist,(2017–2021),"Action, Crime, Mystery",70 min,8.3,"332,294"
11,The Big Bang Theory,(2007–2019),"Comedy, Romance",22 min,8.1,"737,812"
12,Black Mirror,(2011– ),"Drama, Sci-Fi, Thriller",60 min,8.8,"463,005"
13,Sherlock,(2010–2017),"Crime, Drama, Mystery",88 min,9.1,"830,911"
14,Vikings,(2013–2020),"Action, Adventure, Drama",44 min,8.5,"452,158"
15,Pretty Little Liars,(2010–2017),"Drama, Mystery, Romance",44 min,7.4,"154,790"
16,The Vampire Diaries,(2009–2017),"Drama, Fantasy, Horror",43 min,7.7,"290,707"
17,American Horror Story,(2011– ),"Drama, Horror, Thriller",60 min,8,"282,694"
18,Breaking Bad,(2008–2013),"Crime, Drama, Thriller",49 min,9.4,"1,528,516"
19,Lucifer,(2016– ),"Crime, Drama, Fantasy",42 min,8.1,"253,770"
20,Supernatural,(2005–2020),"Drama, Fantasy, Horror",44 min,8.4,"400,187"
21,Prison Break,(2005–2017),"Action, Crime, Drama",44 min,8.3,"487,998"
22,How to Get Away with Murder,(2014–2020),"Crime, Drama, Mystery",43 min,8.1,"134,380"
23,Teen Wolf,(2011–2017),"Action, Drama, Fantasy",41 min,7.6,"131,244"
24,The Simpsons,(1989– ),"Animation, Comedy",22 min,8.6,"372,661"
25,Once Upon a Time,(2011–2018),"Adventure, Fantasy, Romance",60 min,7.7,"211,353"
26,Narcos,(2015–2017),"Biography, Crime, Drama",49 min,8.8,"371,074"
27,Daredevil,(2015–2018),"Action, Crime, Drama",54 min,8.6,"371,308"
28,Friends,(1994–2004),"Comedy, Romance",22 min,8.9,"865,371"
29,How I Met Your Mother,(2005–2014),"Comedy, Romance",22 min,8.3,"618,523"
...,...,...,...,...,...,...
70,Under the Dome,(2013–2015),"Drama, Mystery, Sci-Fi",43 min,6.6,"102,184"
71,The Umbrella Academy,(2019– ),"Action, Adventure, Comedy",60 min,8,"171,270"
72,True Detective,(2014–2019),"Crime, Drama, Mystery",55 min,8.9,"511,067"
73,The OA,(2016–2019),"Drama, Fantasy, Mystery",60 min,7.8,"93,644"
74,Desperate Housewives,(2004–2012),"Comedy, Drama, Mystery",45 min,7.5,"118,656"
75,Better Call Saul,(2015– ),"Crime, Drama",46 min,8.8,"341,580"
76,Bates Motel,(2013–2017),"Drama, Horror, Mystery",45 min,8.1,"99,292"
77,The Punisher,(2017–2019),"Action, Crime, Drama",53 min,8.5,"191,740"
78,Atypical,(2017–2021),"Comedy, Drama",30 min,8.3,"64,445"
79,Dynasty,(2017– ),Drama,42 min,7.3,"16,169"
80,This Is Us,(2016–2022),"Comedy, Drama, Romance",45 min,8.7,"114,669"
81,The Good Place,(2016–2020),"Comedy, Drama, Fantasy",22 min,8.2,"124,141"
82,Iron Fist,(2017–2018),"Action, Adventure, Crime",55 min,6.5,"117,572"
83,The Rain,(2018–2020),"Drama, Sci-Fi, Thriller",45 min,6.3,"32,362"
84,Mindhunter,(2017–2019),"Crime, Drama, Thriller",60 min,8.6,"230,745"
85,Revenge,(2011–2015),"Drama, Mystery, Thriller",44 min,7.8,"114,183"
86,Luke Cage,(2016–2018),"Action, Crime, Drama",55 min,7.3,"119,156"
87,Scandal,(2012–2018),"Drama, Thriller",43 min,7.7,"68,251"
88,The Defenders,(2017),"Action, Adventure, Crime",50 min,7.3,"93,489"
89,Big Little Lies,(2017–2019),"Crime, Drama, Mystery",60 min,8.5,"165,023"
90,Insatiable,(2018–2019),"Comedy, Drama, Thriller",45 min,6.5,"23,670"
91,The Mentalist,(2008–2015),"Crime, Drama, Mystery",43 min,8.1,"168,868"
92,The Crown,(2016– ),"Biography, Drama, History",58 min,8.6,"166,433"
93,Chernobyl,(2019),"Drama, History, Thriller",330 min,9.4,"583,021"
94,iZombie,(2015–2019),"Comedy, Crime, Drama",42 min,7.8,"61,663"
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,602"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,117"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"168,083"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"34,924"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"191,785"

10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code

In [70]:
# Lets first connect to web driver
driver = webdriver.Chrome(r"C:\Users\ASUS\Downloads\chromedriver_win32\chromedriver.exe")


# Opening the UCI machine learning website
driver.get("https://archive.ics.uci.edu/")

In [71]:

# Viewing all the datasets by passing xpath
driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b").click()

In [72]:
#Scraping the data by passing xpath 
name = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[1]")
#Making a list and storing all the scraped names into it
Name=[]
for i in name:
    if i.text is None :
        Name.append("-") 
    else:
        Name.append(i.text)
#Scraping the data by passing xpath         
datatype=driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[2]")
#Making a list and storing all the scraped datatypes into it
Datatype=[]
for i in datatype:
    if i.text is None :
        Datatype.append("-") 
    else:
        Datatype.append(i.text)
#Scraping the data by passing xpath
task = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[3]")
#Making a list and storing all the scraped tasks into it
Task=[]
for i in task:
    if i.text is None :
        Task.append("-") 
    else:
        Task.append(i.text)
#Scraping the data by passing xpath
attribute_types = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[4]")
#Making a list and storing all the scraped attribute types into it
Attribute_types=[]
for i in attribute_types:
    if i.text is None :
        Attribute_types.append("-") 
    else:
        Attribute_types.append(i.text)
#Scraping the data by passing xpath
Instances_no = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[5]")
#Making a list and storing all the scraped instances number into it
Instances=[]
for i in Instances_no:
    if i.text is None :
        Instances.append("-") 
    else:
        Instances.append(i.text)
#Scraping the data by passing xpath
Attributes_no = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[6]")
#Making a list and storing all the scraped no. of attributes into it
Attributes=[]
for i in Attributes_no:
    if i.text is None :
        Attributes.append("-") 
    else:
        Attributes.append(i.text)
        
#Scraping the data by passing xpath
year = driver.find_elements_by_xpath("//table[@border='1']/tbody/tr/td[7]")
#Making a list and storing all the scraped years into it
Year=[]
for i in year:
    if i.text is None :
        Year.append("-") 
    else:
        Year.append(i.text)

In [73]:
#Checking the length of all the columns
print(len(Name),len(Datatype),len(Attribute_types),len(Instances),len(Attributes),len(Year))

589 589 589 589 589 589

In [74]:
#Saving all the scraped data into a DataFrame(UCI)
UCI=pd.DataFrame({})
UCI['Dataset Name']=Name
UCI['Data Type']=Datatype
UCI['Attribute Type']=Attribute_types
UCI['No of Instances']=Instances
UCI['No of Attribute']=Attributes
UCI['Year']=Year
#Viewing the DataFrame
UCI

,Dataset Name,Data Type,Attribute Type,No of Instances,No of Attribute,Year
0,Name,Data Types,Attribute Types,# Instances,# Attributes,Year
1,Abalone,Multivariate,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,"Categorical, Integer, Real",452,279,1998
6,Artificial Characters,Multivariate,"Categorical, Integer, Real",6000,7,1992
7,Audiology (Original),Multivariate,Categorical,226,,1987
8,Audiology (Standardized),Multivariate,Categorical,226,69,1992
9,Auto MPG,Multivariate,"Categorical, Real",398,8,1993
10,Automobile,Multivariate,"Categorical, Integer, Real",205,26,1987
11,Badges,"Univariate, Text",,294,1,1994
12,Balance Scale,Multivariate,Categorical,625,4,1994
13,Balloons,Multivariate,Categorical,16,4,
14,Breast Cancer,Multivariate,Categorical,286,9,1988
15,Breast Cancer Wisconsin (Original),Multivariate,Integer,699,10,1992
16,Breast Cancer Wisconsin (Prognostic),Multivariate,Real,198,34,1995
17,Breast Cancer Wisconsin (Diagnostic),Multivariate,Real,569,32,1995
18,Pittsburgh Bridges,Multivariate,"Categorical, Integer",108,13,1990
19,Car Evaluation,Multivariate,Categorical,1728,6,1997
20,Census Income,Multivariate,"Categorical, Integer",48842,14,1996
21,Chess (King-Rook vs. King-Knight),"Multivariate, Data-Generator","Categorical, Integer",,22,1988
22,Chess (King-Rook vs. King-Pawn),Multivariate,Categorical,3196,36,1989
23,Chess (King-Rook vs. King),Multivariate,"Categorical, Integer",28056,6,1994
24,Chess (Domain Theories),Domain-Theory,,,,
25,Bach Chorales,"Univariate, Time-Series","Categorical, Integer",100,6,
26,Connect-4,"Multivariate, Spatial",Categorical,67557,42,1995
27,Credit Approval,Multivariate,"Categorical, Integer, Real",690,15,
28,Japanese Credit Screening,"Multivariate, Domain-Theory","Categorical, Real, Integer",125,,1992
29,Computer Hardware,Multivariate,Integer,209,9,1987
...,...,...,...,...,...,...
559,Intelligent Media Accelerometer and Gyroscop...,Time-Series,Real,800,9,2020
560,Myocardial infarction complications,Multivariate,Real,1700,124,2020
561,Hungarian Chickenpox Cases,Time-Series,Real,521,20,2021
562,Simulated data for survival modelling,"Multivariate, Time-Series","Integer, Real",120000,25,2018
563,Student Performance on an entrance examination,Multivariate,,666,11,2018
564,Chemical Composition of Ceramic Samples,Multivariate,Real,88,19,2019
565,Labeled Text Forum Threads Dataset,Text,Integer,200,9,2019
566,Stock keeping units,Multivariate,"Integer, Real",2279,9,2019
567,BLE RSSI dataset for Indoor localization,"Sequential, Time-Series",Integer,23570,5,2019
568,Basketball dataset,Time-Series,Integer,10000,7,2019
569,GitHub MUSAE,Multivariate,,37700,4006,2019
570,Anticancer peptides,Sequential,,1850,2,2019
571,Monolithic Columns in Troad and Mysia Region,Multivariate,Real,11,19,2020
572,Gender by Name,Text,,147270,4,2020
573,Iranian Churn Dataset,Multivariate,Integer,3150,13,2020
574,Unmanned Aerial Vehicle (UAV) Intrusion Dete...,Multivariate,Real,17256,55,2020
575,Shoulder Implant Manufacture Classification,Multivariate,,597,1,2020
576,LastFM Asia Social Network,Multivariate,,7624,7842,2020
577,Wheat kernels,Multivariate,Real,314,15,2020
578,Productivity Prediction of Garment Employees,"Multivariate, Time-Series","Integer, Real",1197,15,2020
579,Multi-view Brain Networks,Multivariate,Integer,70,70,2020
580,LastFM Asia Social Network,Multivariate,,7624,7842,2020
581,Wisesight Sentiment Corpus,"Multivariate, Text",,26737,4,2020
582,AI4I 2020 Predictive Maintenance Dataset,"Multivariate, Time-Series",Real,10000,14,2020
583,Dry Bean Dataset,Multivariate,"Integer, Real",13611,17,2020
584,in-vehicle coupon recommendation,Multivariate,,12684,23,2020
585,Gait Classification,Multivariate,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Real,557,5,2021